// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pulse.proto

package pulsepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pulse_Subscribe_FullMethodName       = "/robin.pulse.v1.Pulse/Subscribe"
	Pulse_SendTransaction_FullMethodName = "/robin.pulse.v1.Pulse/SendTransaction"
)

// PulseClient is the client API for Pulse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Pulse: live transaction stream for Robinhood Chain with three commitment levels.
//
//	RECEIVED  - the transaction as accepted by the sequencer, before execution
//	            (hash, to, value, input, raw_tx, feed_sequence). Logs are synthetic markers.
//	PROCESSED - executed (real logs, gas, success); the block is not yet sealed.
//	CONFIRMED - the block is sealed and canonical.
//
// A subscription delivers every matching transaction once, at its chosen level. BlockStatus messages
// report when a block is sealed or a processed block is invalidated, so PROCESSED consumers can reconcile.
// There is no replay and no exactly-once guarantee: after a reconnect, reconcile via RPC.
type PulseClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate], error)
	// Submit a signed transaction to the sequencer through Eira and, optionally, wait until it is
	// observed at RECEIVED level, in which case its position in the block is returned.
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
}

type pulseClient struct {
	cc grpc.ClientConnInterface
}

func NewPulseClient(cc grpc.ClientConnInterface) PulseClient {
	return &pulseClient{cc}
}

func (c *pulseClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Pulse_ServiceDesc.Streams[0], Pulse_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pulse_SubscribeClient = grpc.BidiStreamingClient[SubscribeRequest, SubscribeUpdate]

func (c *pulseClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, Pulse_SendTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PulseServer is the server API for Pulse service.
// All implementations must embed UnimplementedPulseServer
// for forward compatibility.
//
// Pulse: live transaction stream for Robinhood Chain with three commitment levels.
//
//	RECEIVED  - the transaction as accepted by the sequencer, before execution
//	            (hash, to, value, input, raw_tx, feed_sequence). Logs are synthetic markers.
//	PROCESSED - executed (real logs, gas, success); the block is not yet sealed.
//	CONFIRMED - the block is sealed and canonical.
//
// A subscription delivers every matching transaction once, at its chosen level. BlockStatus messages
// report when a block is sealed or a processed block is invalidated, so PROCESSED consumers can reconcile.
// There is no replay and no exactly-once guarantee: after a reconnect, reconcile via RPC.
type PulseServer interface {
	Subscribe(grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]) error
	// Submit a signed transaction to the sequencer through Eira and, optionally, wait until it is
	// observed at RECEIVED level, in which case its position in the block is returned.
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	mustEmbedUnimplementedPulseServer()
}

// UnimplementedPulseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPulseServer struct{}

func (UnimplementedPulseServer) Subscribe(grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPulseServer) SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedPulseServer) mustEmbedUnimplementedPulseServer() {}
func (UnimplementedPulseServer) testEmbeddedByValue()               {}

// UnsafePulseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PulseServer will
// result in compilation errors.
type UnsafePulseServer interface {
	mustEmbedUnimplementedPulseServer()
}

func RegisterPulseServer(s grpc.ServiceRegistrar, srv PulseServer) {
	// If the following call panics, it indicates UnimplementedPulseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pulse_ServiceDesc, srv)
}

func _Pulse_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PulseServer).Subscribe(&grpc.GenericServerStream[SubscribeRequest, SubscribeUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pulse_SubscribeServer = grpc.BidiStreamingServer[SubscribeRequest, SubscribeUpdate]

func _Pulse_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PulseServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pulse_SendTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PulseServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pulse_ServiceDesc is the grpc.ServiceDesc for Pulse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pulse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robin.pulse.v1.Pulse",
	HandlerType: (*PulseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _Pulse_SendTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Pulse_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pulse.proto",
}
