// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pulse.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PROCESSED is the zero value: a subscription that does not set a level gets PROCESSED.
type Commitment int32

const (
	Commitment_PROCESSED Commitment = 0
	Commitment_CONFIRMED Commitment = 1
	Commitment_RECEIVED  Commitment = 2
)

// Enum value maps for Commitment.
var (
	Commitment_name = map[int32]string{
		0: "PROCESSED",
		1: "CONFIRMED",
		2: "RECEIVED",
	}
	Commitment_value = map[string]int32{
		"PROCESSED": 0,
		"CONFIRMED": 1,
		"RECEIVED":  2,
	}
)

func (x Commitment) Enum() *Commitment {
	p := new(Commitment)
	*p = x
	return p
}

func (x Commitment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Commitment) Descriptor() protoreflect.EnumDescriptor {
	return file_pulse_proto_enumTypes[0].Descriptor()
}

func (Commitment) Type() protoreflect.EnumType {
	return &file_pulse_proto_enumTypes[0]
}

func (x Commitment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Commitment.Descriptor instead.
func (Commitment) EnumDescriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{0}
}

type SendTransactionResponse_WaitStatus int32

const (
	SendTransactionResponse_NOT_REQUESTED      SendTransactionResponse_WaitStatus = 0
	SendTransactionResponse_OBSERVED           SendTransactionResponse_WaitStatus = 1 // `received` is set
	SendTransactionResponse_TIMED_OUT          SendTransactionResponse_WaitStatus = 2 // accepted, not observed within the timeout
	SendTransactionResponse_SOURCE_UNAVAILABLE SendTransactionResponse_WaitStatus = 3 // accepted, the RECEIVED level was unavailable while waiting
)

// Enum value maps for SendTransactionResponse_WaitStatus.
var (
	SendTransactionResponse_WaitStatus_name = map[int32]string{
		0: "NOT_REQUESTED",
		1: "OBSERVED",
		2: "TIMED_OUT",
		3: "SOURCE_UNAVAILABLE",
	}
	SendTransactionResponse_WaitStatus_value = map[string]int32{
		"NOT_REQUESTED":      0,
		"OBSERVED":           1,
		"TIMED_OUT":          2,
		"SOURCE_UNAVAILABLE": 3,
	}
)

func (x SendTransactionResponse_WaitStatus) Enum() *SendTransactionResponse_WaitStatus {
	p := new(SendTransactionResponse_WaitStatus)
	*p = x
	return p
}

func (x SendTransactionResponse_WaitStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendTransactionResponse_WaitStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pulse_proto_enumTypes[1].Descriptor()
}

func (SendTransactionResponse_WaitStatus) Type() protoreflect.EnumType {
	return &file_pulse_proto_enumTypes[1]
}

func (x SendTransactionResponse_WaitStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendTransactionResponse_WaitStatus.Descriptor instead.
func (SendTransactionResponse_WaitStatus) EnumDescriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{1, 0}
}

type BlockStatus_Status int32

const (
	BlockStatus_SEALED      BlockStatus_Status = 0
	BlockStatus_INVALIDATED BlockStatus_Status = 1
)

// Enum value maps for BlockStatus_Status.
var (
	BlockStatus_Status_name = map[int32]string{
		0: "SEALED",
		1: "INVALIDATED",
	}
	BlockStatus_Status_value = map[string]int32{
		"SEALED":      0,
		"INVALIDATED": 1,
	}
)

func (x BlockStatus_Status) Enum() *BlockStatus_Status {
	p := new(BlockStatus_Status)
	*p = x
	return p
}

func (x BlockStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pulse_proto_enumTypes[2].Descriptor()
}

func (BlockStatus_Status) Type() protoreflect.EnumType {
	return &file_pulse_proto_enumTypes[2]
}

func (x BlockStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockStatus_Status.Descriptor instead.
func (BlockStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{11, 0}
}

// FEED: a RECEIVED-level event, not executed. The same transaction is delivered as USER at
// PROCESSED and CONFIRMED level to subscriptions at those levels.
type Transaction_Kind int32

const (
	Transaction_START_BLOCK     Transaction_Kind = 0
	Transaction_USER            Transaction_Kind = 1
	Transaction_SCHEDULED_RETRY Transaction_Kind = 2
	Transaction_FEED            Transaction_Kind = 3
)

// Enum value maps for Transaction_Kind.
var (
	Transaction_Kind_name = map[int32]string{
		0: "START_BLOCK",
		1: "USER",
		2: "SCHEDULED_RETRY",
		3: "FEED",
	}
	Transaction_Kind_value = map[string]int32{
		"START_BLOCK":     0,
		"USER":            1,
		"SCHEDULED_RETRY": 2,
		"FEED":            3,
	}
)

func (x Transaction_Kind) Enum() *Transaction_Kind {
	p := new(Transaction_Kind)
	*p = x
	return p
}

func (x Transaction_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pulse_proto_enumTypes[3].Descriptor()
}

func (Transaction_Kind) Type() protoreflect.EnumType {
	return &file_pulse_proto_enumTypes[3]
}

func (x Transaction_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_Kind.Descriptor instead.
func (Transaction_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{12, 0}
}

type SendTransactionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RawTransaction    []byte                 `protobuf:"bytes,1,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`             // signed transaction bytes (typed envelope), signed by the client
	WaitForReceived   bool                   `protobuf:"varint,2,opt,name=wait_for_received,json=waitForReceived,proto3" json:"wait_for_received,omitempty"`       // wait for the RECEIVED observation before answering
	ReceivedTimeoutMs uint32                 `protobuf:"varint,3,opt,name=received_timeout_ms,json=receivedTimeoutMs,proto3" json:"received_timeout_ms,omitempty"` // 0 = 3000 ms; at most 10000 ms; counted after the submission is accepted
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	mi := &file_pulse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{0}
}

func (x *SendTransactionRequest) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

func (x *SendTransactionRequest) GetWaitForReceived() bool {
	if x != nil {
		return x.WaitForReceived
	}
	return false
}

func (x *SendTransactionRequest) GetReceivedTimeoutMs() uint32 {
	if x != nil {
		return x.ReceivedTimeoutMs
	}
	return 0
}

// Errors: INVALID_ARGUMENT / FAILED_PRECONDITION carry the sequencer's own rejection text, and the
// transaction was not sequenced. UNAVAILABLE "submission outcome unknown" means the submission may
// still have been sequenced: the transaction hash is in the `x-eira-transaction-hash` response header,
// check the receipt before reusing the nonce. RESOURCE_EXHAUSTED is the per-plan send rate.
type SendTransactionResponse struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	TransactionHash []byte                             `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	WaitStatus      SendTransactionResponse_WaitStatus `protobuf:"varint,5,opt,name=wait_status,json=waitStatus,proto3,enum=robin.pulse.v1.SendTransactionResponse_WaitStatus" json:"wait_status,omitempty"`
	Received        *ReceivedPosition                  `protobuf:"bytes,6,opt,name=received,proto3" json:"received,omitempty"` // only when wait_status is OBSERVED; execution is verified via the receipt
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	mi := &file_pulse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{1}
}

func (x *SendTransactionResponse) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *SendTransactionResponse) GetWaitStatus() SendTransactionResponse_WaitStatus {
	if x != nil {
		return x.WaitStatus
	}
	return SendTransactionResponse_NOT_REQUESTED
}

func (x *SendTransactionResponse) GetReceived() *ReceivedPosition {
	if x != nil {
		return x.Received
	}
	return nil
}

type ReceivedPosition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FeedSequence     uint64                 `protobuf:"varint,1,opt,name=feed_sequence,json=feedSequence,proto3" json:"feed_sequence,omitempty"`             // block, as on RECEIVED events
	TransactionIndex uint64                 `protobuf:"varint,2,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"` // position in the block, as on RECEIVED events
	BlockTimestamp   uint64                 `protobuf:"varint,6,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`       // block timestamp in seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceivedPosition) Reset() {
	*x = ReceivedPosition{}
	mi := &file_pulse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedPosition) ProtoMessage() {}

func (x *ReceivedPosition) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedPosition.ProtoReflect.Descriptor instead.
func (*ReceivedPosition) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{2}
}

func (x *ReceivedPosition) GetFeedSequence() uint64 {
	if x != nil {
		return x.FeedSequence
	}
	return 0
}

func (x *ReceivedPosition) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *ReceivedPosition) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

type SubscribeRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*SubscribeRequest_Replace
	//	*SubscribeRequest_Ping
	Action        isSubscribeRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_pulse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SubscribeRequest) GetAction() isSubscribeRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SubscribeRequest) GetReplace() *Subscription {
	if x != nil {
		if x, ok := x.Action.(*SubscribeRequest_Replace); ok {
			return x.Replace
		}
	}
	return nil
}

func (x *SubscribeRequest) GetPing() uint64 {
	if x != nil {
		if x, ok := x.Action.(*SubscribeRequest_Ping); ok {
			return x.Ping
		}
	}
	return 0
}

type isSubscribeRequest_Action interface {
	isSubscribeRequest_Action()
}

type SubscribeRequest_Replace struct {
	Replace *Subscription `protobuf:"bytes,2,opt,name=replace,proto3,oneof"`
}

type SubscribeRequest_Ping struct {
	Ping uint64 `protobuf:"varint,3,opt,name=ping,proto3,oneof"`
}

func (*SubscribeRequest_Replace) isSubscribeRequest_Action() {}

func (*SubscribeRequest_Ping) isSubscribeRequest_Action() {}

type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Named filters are OR'ed; conditions inside one filter are AND'ed.
	// {"all": {}} selects every transaction, including transactions without logs.
	// An empty map pauses delivery. replace atomically replaces all filters.
	Transactions map[string]*TransactionFilter `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Level at which transactions are delivered (default PROCESSED).
	Commitment Commitment `protobuf:"varint,2,opt,name=commitment,proto3,enum=robin.pulse.v1.Commitment" json:"commitment,omitempty"`
	// RECEIVED level only: deliver transactions in UpdateBatch messages. The first transaction that becomes
	// available is sent at once; transactions that follow it closely are grouped into one message. The
	// transactions and their order are the same as without batching; only the number of messages differs.
	// Recommended for clients with a high per-message cost (Python, Node.js).
	Batch         bool `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_pulse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription) GetTransactions() map[string]*TransactionFilter {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Subscription) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_PROCESSED
}

func (x *Subscription) GetBatch() bool {
	if x != nil {
		return x.Batch
	}
	return false
}

type TransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matching is scoped to LOG EMITTER addresses. Raw 20-byte addresses.
	// A matching transaction is delivered with ALL its logs.
	AddressInclude  [][]byte `protobuf:"bytes,1,rep,name=address_include,json=addressInclude,proto3" json:"address_include,omitempty"`    // empty, or ANY emitter matches
	AddressExclude  [][]byte `protobuf:"bytes,2,rep,name=address_exclude,json=addressExclude,proto3" json:"address_exclude,omitempty"`    // NONE of the emitters may match
	AddressRequired [][]byte `protobuf:"bytes,3,rep,name=address_required,json=addressRequired,proto3" json:"address_required,omitempty"` // ALL listed emitters must occur
	Failed          *bool    `protobuf:"varint,4,opt,name=failed,proto3,oneof" json:"failed,omitempty"`
	TransactionHash []byte   `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3,oneof" json:"transaction_hash,omitempty"` // raw 32-byte hash
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_pulse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionFilter) GetAddressInclude() [][]byte {
	if x != nil {
		return x.AddressInclude
	}
	return nil
}

func (x *TransactionFilter) GetAddressExclude() [][]byte {
	if x != nil {
		return x.AddressExclude
	}
	return nil
}

func (x *TransactionFilter) GetAddressRequired() [][]byte {
	if x != nil {
		return x.AddressRequired
	}
	return nil
}

func (x *TransactionFilter) GetFailed() bool {
	if x != nil && x.Failed != nil {
		return *x.Failed
	}
	return false
}

func (x *TransactionFilter) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

type SubscribeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of the filters this update matched.
	Filters []string `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	// Changes when the server restarts; sequence then starts over. sequence counts all source events,
	// including filtered-out ones, so sequence gaps alone do not imply loss.
	StreamEpoch []byte `protobuf:"bytes,2,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`
	Sequence    uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Update:
	//
	//	*SubscribeUpdate_Transaction
	//	*SubscribeUpdate_Ack
	//	*SubscribeUpdate_Pong
	//	*SubscribeUpdate_BlockStatus
	//	*SubscribeUpdate_SourceStatus
	//	*SubscribeUpdate_Batch
	Update        isSubscribeUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUpdate) Reset() {
	*x = SubscribeUpdate{}
	mi := &file_pulse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUpdate) ProtoMessage() {}

func (x *SubscribeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUpdate.ProtoReflect.Descriptor instead.
func (*SubscribeUpdate) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeUpdate) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SubscribeUpdate) GetStreamEpoch() []byte {
	if x != nil {
		return x.StreamEpoch
	}
	return nil
}

func (x *SubscribeUpdate) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SubscribeUpdate) GetUpdate() isSubscribeUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *SubscribeUpdate) GetTransaction() *Transaction {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetAck() *SubscriptionAck {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetBlockStatus() *BlockStatus {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_BlockStatus); ok {
			return x.BlockStatus
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetSourceStatus() *SourceStatus {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_SourceStatus); ok {
			return x.SourceStatus
		}
	}
	return nil
}

func (x *SubscribeUpdate) GetBatch() *UpdateBatch {
	if x != nil {
		if x, ok := x.Update.(*SubscribeUpdate_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isSubscribeUpdate_Update interface {
	isSubscribeUpdate_Update()
}

type SubscribeUpdate_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,4,opt,name=transaction,proto3,oneof"`
}

type SubscribeUpdate_Ack struct {
	Ack *SubscriptionAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type SubscribeUpdate_Pong struct {
	Pong *Pong `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

type SubscribeUpdate_BlockStatus struct {
	BlockStatus *BlockStatus `protobuf:"bytes,7,opt,name=block_status,json=blockStatus,proto3,oneof"`
}

type SubscribeUpdate_SourceStatus struct {
	// Availability of the source behind a level. Sent to subscriptions at the RECEIVED level when that
	// source disconnects or reconnects: a reconciliation boundary for RECEIVED events.
	// PROCESSED and CONFIRMED delivery continues.
	SourceStatus *SourceStatus `protobuf:"bytes,8,opt,name=source_status,json=sourceStatus,proto3,oneof"`
}

type SubscribeUpdate_Batch struct {
	// Consecutive transaction updates, when the subscription sets batch.
	Batch *UpdateBatch `protobuf:"bytes,9,opt,name=batch,proto3,oneof"`
}

func (*SubscribeUpdate_Transaction) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_Ack) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_Pong) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_BlockStatus) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_SourceStatus) isSubscribeUpdate_Update() {}

func (*SubscribeUpdate_Batch) isSubscribeUpdate_Update() {}

// Each element is a complete update (filters, stream_epoch, sequence, transaction), exactly as it would be
// delivered without batching; the enclosing update carries nothing else.
type UpdateBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*SubscribeUpdate     `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBatch) Reset() {
	*x = UpdateBatch{}
	mi := &file_pulse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBatch) ProtoMessage() {}

func (x *UpdateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBatch.ProtoReflect.Descriptor instead.
func (*UpdateBatch) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBatch) GetUpdates() []*SubscribeUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type SourceStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Commitment Commitment             `protobuf:"varint,1,opt,name=commitment,proto3,enum=robin.pulse.v1.Commitment" json:"commitment,omitempty"`
	Connected  bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	// Increments on every reconnect of that source; events before and after may overlap or gap.
	SourceEpoch   uint64 `protobuf:"varint,3,opt,name=source_epoch,json=sourceEpoch,proto3" json:"source_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceStatus) Reset() {
	*x = SourceStatus{}
	mi := &file_pulse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceStatus) ProtoMessage() {}

func (x *SourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceStatus.ProtoReflect.Descriptor instead.
func (*SourceStatus) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{8}
}

func (x *SourceStatus) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_PROCESSED
}

func (x *SourceStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *SourceStatus) GetSourceEpoch() uint64 {
	if x != nil {
		return x.SourceEpoch
	}
	return 0
}

type SubscriptionAck struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// All updates after this ACK use this subscription until the next ACK.
	FilterCount uint32 `protobuf:"varint,2,opt,name=filter_count,json=filterCount,proto3" json:"filter_count,omitempty"`
	// Level in effect after this ACK.
	Commitment    Commitment `protobuf:"varint,3,opt,name=commitment,proto3,enum=robin.pulse.v1.Commitment" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionAck) Reset() {
	*x = SubscriptionAck{}
	mi := &file_pulse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionAck) ProtoMessage() {}

func (x *SubscriptionAck) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionAck.ProtoReflect.Descriptor instead.
func (*SubscriptionAck) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionAck) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *SubscriptionAck) GetFilterCount() uint32 {
	if x != nil {
		return x.FilterCount
	}
	return 0
}

func (x *SubscriptionAck) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_PROCESSED
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pulse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{10}
}

func (x *Pong) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Pong) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BlockStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber  uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash    []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`           // empty until the block is sealed
	FeedSequence uint64                 `protobuf:"varint,3,opt,name=feed_sequence,json=feedSequence,proto3" json:"feed_sequence,omitempty"` // 0 if unknown
	Status       BlockStatus_Status     `protobuf:"varint,4,opt,name=status,proto3,enum=robin.pulse.v1.BlockStatus_Status" json:"status,omitempty"`
	// Transaction count of the sealed block (0 if unknown).
	TransactionCount uint32 `protobuf:"varint,5,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	// False when PROCESSED events did not cover every transaction of the block (the stream attached
	// mid-block): CONFIRMED delivery for this block is incomplete.
	CoverageComplete bool `protobuf:"varint,6,opt,name=coverage_complete,json=coverageComplete,proto3" json:"coverage_complete,omitempty"`
	// Execution attempt at this height; see Transaction.attempt.
	Attempt uint32 `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Header fields of the sealed block (empty or 0 on INVALIDATED), so a consumer can complete the
	// block header without an RPC round trip.
	ParentHash    []byte `protobuf:"bytes,8,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Timestamp     uint64 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BaseFeePerGas uint64 `protobuf:"varint,10,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockStatus) Reset() {
	*x = BlockStatus{}
	mi := &file_pulse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockStatus) ProtoMessage() {}

func (x *BlockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockStatus.ProtoReflect.Descriptor instead.
func (*BlockStatus) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{11}
}

func (x *BlockStatus) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockStatus) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockStatus) GetFeedSequence() uint64 {
	if x != nil {
		return x.FeedSequence
	}
	return 0
}

func (x *BlockStatus) GetStatus() BlockStatus_Status {
	if x != nil {
		return x.Status
	}
	return BlockStatus_SEALED
}

func (x *BlockStatus) GetTransactionCount() uint32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *BlockStatus) GetCoverageComplete() bool {
	if x != nil {
		return x.CoverageComplete
	}
	return false
}

func (x *BlockStatus) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *BlockStatus) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockStatus) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockStatus) GetBaseFeePerGas() uint64 {
	if x != nil {
		return x.BaseFeePerGas
	}
	return 0
}

type Transaction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber      uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionIndex uint64                 `protobuf:"varint,2,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	TransactionHash  []byte                 `protobuf:"bytes,3,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	FrontierId       []byte                 `protobuf:"bytes,4,opt,name=frontier_id,json=frontierId,proto3" json:"frontier_id,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Success          bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Kind             Transaction_Kind       `protobuf:"varint,7,opt,name=kind,proto3,enum=robin.pulse.v1.Transaction_Kind" json:"kind,omitempty"`
	Logs             []*Log                 `protobuf:"bytes,8,rep,name=logs,proto3" json:"logs,omitempty"`
	// Always true. PROCESSED events can be invalidated by a BlockStatus INVALIDATED message.
	Precanonical bool `protobuf:"varint,9,opt,name=precanonical,proto3" json:"precanonical,omitempty"`
	// RECEIVED events: callee and calldata, feed sequence number, provisional = true.
	To           []byte `protobuf:"bytes,10,opt,name=to,proto3" json:"to,omitempty"`
	Input        []byte `protobuf:"bytes,11,opt,name=input,proto3" json:"input,omitempty"`
	FeedSequence uint64 `protobuf:"varint,12,opt,name=feed_sequence,json=feedSequence,proto3" json:"feed_sequence,omitempty"`
	Provisional  bool   `protobuf:"varint,13,opt,name=provisional,proto3" json:"provisional,omitempty"`
	// Level this event was delivered at.
	Commitment Commitment `protobuf:"varint,14,opt,name=commitment,proto3,enum=robin.pulse.v1.Commitment" json:"commitment,omitempty"`
	// Execution attempt at this block height (0 = first). PROCESSED events of an attempt that is later
	// INVALIDATED must be dropped; the next attempt re-publishes with attempt + 1.
	Attempt uint32 `protobuf:"varint,15,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// RECEIVED events only: the signed transaction exactly as the sequencer carries it (typed envelope,
	// what eth_sendRawTransaction takes) and its value (big-endian, no leading zeros, empty = 0).
	// Sender recovery is left to the consumer. Empty on other levels.
	RawTx []byte `protobuf:"bytes,16,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	Value []byte `protobuf:"bytes,17,opt,name=value,proto3" json:"value,omitempty"`
	// RECEIVED events only: the block timestamp (seconds) and the L1 block number from the header of the
	// feed message that carries the block. Both are known before the first transaction of the block is
	// delivered, so a consumer that needs execution context does not have to wait for anything else.
	// 0 when the header could not be read.
	Timestamp     uint64 `protobuf:"varint,18,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	L1BlockNumber uint64 `protobuf:"varint,19,opt,name=l1_block_number,json=l1BlockNumber,proto3" json:"l1_block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_pulse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Transaction) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *Transaction) GetTransactionHash() []byte {
	if x != nil {
		return x.TransactionHash
	}
	return nil
}

func (x *Transaction) GetFrontierId() []byte {
	if x != nil {
		return x.FrontierId
	}
	return nil
}

func (x *Transaction) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Transaction) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Transaction) GetKind() Transaction_Kind {
	if x != nil {
		return x.Kind
	}
	return Transaction_START_BLOCK
}

func (x *Transaction) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Transaction) GetPrecanonical() bool {
	if x != nil {
		return x.Precanonical
	}
	return false
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Transaction) GetFeedSequence() uint64 {
	if x != nil {
		return x.FeedSequence
	}
	return 0
}

func (x *Transaction) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

func (x *Transaction) GetCommitment() Commitment {
	if x != nil {
		return x.Commitment
	}
	return Commitment_PROCESSED
}

func (x *Transaction) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Transaction) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

func (x *Transaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Transaction) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetL1BlockNumber() uint64 {
	if x != nil {
		return x.L1BlockNumber
	}
	return 0
}

type Log struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Address []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics  [][]byte               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data    []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// On RECEIVED events logs are synthetic markers: 0xFFFFFFFF carries the callee address,
	// 0xFFFFFFFE a predicted Uniswap V4 PoolManager Swap for callees that recently emitted real Swaps.
	// On PROCESSED and CONFIRMED events this is the index of the log within the transaction.
	TransactionLogIndex uint32 `protobuf:"varint,4,opt,name=transaction_log_index,json=transactionLogIndex,proto3" json:"transaction_log_index,omitempty"`
	// Block-wide log index (eth_getLogs logIndex) on PROCESSED and CONFIRMED events.
	// 0xFFFFFFFF when unknown (stream attached mid-block) and on RECEIVED synthetic logs.
	LogIndex      uint32 `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_pulse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_pulse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_pulse_proto_rawDescGZIP(), []int{13}
}

func (x *Log) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Log) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetTransactionLogIndex() uint32 {
	if x != nil {
		return x.TransactionLogIndex
	}
	return 0
}

func (x *Log) GetLogIndex() uint32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

var File_pulse_proto protoreflect.FileDescriptor

const file_pulse_proto_rawDesc = "" +
	"\n" +
	"\vpulse.proto\x12\x0erobin.pulse.v1\"\x9d\x01\n" +
	"\x16SendTransactionRequest\x12'\n" +
	"\x0fraw_transaction\x18\x01 \x01(\fR\x0erawTransaction\x12*\n" +
	"\x11wait_for_received\x18\x02 \x01(\bR\x0fwaitForReceived\x12.\n" +
	"\x13received_timeout_ms\x18\x03 \x01(\rR\x11receivedTimeoutMs\"\xc5\x02\n" +
	"\x17SendTransactionResponse\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\fR\x0ftransactionHash\x12S\n" +
	"\vwait_status\x18\x05 \x01(\x0e22.robin.pulse.v1.SendTransactionResponse.WaitStatusR\n" +
	"waitStatus\x12<\n" +
	"\breceived\x18\x06 \x01(\v2 .robin.pulse.v1.ReceivedPositionR\breceived\"T\n" +
	"\n" +
	"WaitStatus\x12\x11\n" +
	"\rNOT_REQUESTED\x10\x00\x12\f\n" +
	"\bOBSERVED\x10\x01\x12\r\n" +
	"\tTIMED_OUT\x10\x02\x12\x16\n" +
	"\x12SOURCE_UNAVAILABLE\x10\x03J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\a\x10\b\"\x9f\x01\n" +
	"\x10ReceivedPosition\x12#\n" +
	"\rfeed_sequence\x18\x01 \x01(\x04R\ffeedSequence\x12+\n" +
	"\x11transaction_index\x18\x02 \x01(\x04R\x10transactionIndex\x12'\n" +
	"\x0fblock_timestamp\x18\x06 \x01(\x04R\x0eblockTimestampJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06\"\x8b\x01\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x128\n" +
	"\areplace\x18\x02 \x01(\v2\x1c.robin.pulse.v1.SubscriptionH\x00R\areplace\x12\x14\n" +
	"\x04ping\x18\x03 \x01(\x04H\x00R\x04pingB\b\n" +
	"\x06action\"\x98\x02\n" +
	"\fSubscription\x12R\n" +
	"\ftransactions\x18\x01 \x03(\v2..robin.pulse.v1.Subscription.TransactionsEntryR\ftransactions\x12:\n" +
	"\n" +
	"commitment\x18\x02 \x01(\x0e2\x1a.robin.pulse.v1.CommitmentR\n" +
	"commitment\x12\x14\n" +
	"\x05batch\x18\x03 \x01(\bR\x05batch\x1ab\n" +
	"\x11TransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.robin.pulse.v1.TransactionFilterR\x05value:\x028\x01\"\xfd\x01\n" +
	"\x11TransactionFilter\x12'\n" +
	"\x0faddress_include\x18\x01 \x03(\fR\x0eaddressInclude\x12'\n" +
	"\x0faddress_exclude\x18\x02 \x03(\fR\x0eaddressExclude\x12)\n" +
	"\x10address_required\x18\x03 \x03(\fR\x0faddressRequired\x12\x1b\n" +
	"\x06failed\x18\x04 \x01(\bH\x00R\x06failed\x88\x01\x01\x12.\n" +
	"\x10transaction_hash\x18\x05 \x01(\fH\x01R\x0ftransactionHash\x88\x01\x01B\t\n" +
	"\a_failedB\x13\n" +
	"\x11_transaction_hash\"\xd2\x03\n" +
	"\x0fSubscribeUpdate\x12\x18\n" +
	"\afilters\x18\x01 \x03(\tR\afilters\x12!\n" +
	"\fstream_epoch\x18\x02 \x01(\fR\vstreamEpoch\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12?\n" +
	"\vtransaction\x18\x04 \x01(\v2\x1b.robin.pulse.v1.TransactionH\x00R\vtransaction\x123\n" +
	"\x03ack\x18\x05 \x01(\v2\x1f.robin.pulse.v1.SubscriptionAckH\x00R\x03ack\x12*\n" +
	"\x04pong\x18\x06 \x01(\v2\x14.robin.pulse.v1.PongH\x00R\x04pong\x12@\n" +
	"\fblock_status\x18\a \x01(\v2\x1b.robin.pulse.v1.BlockStatusH\x00R\vblockStatus\x12C\n" +
	"\rsource_status\x18\b \x01(\v2\x1c.robin.pulse.v1.SourceStatusH\x00R\fsourceStatus\x123\n" +
	"\x05batch\x18\t \x01(\v2\x1b.robin.pulse.v1.UpdateBatchH\x00R\x05batchB\b\n" +
	"\x06update\"H\n" +
	"\vUpdateBatch\x129\n" +
	"\aupdates\x18\x01 \x03(\v2\x1f.robin.pulse.v1.SubscribeUpdateR\aupdates\"\x8b\x01\n" +
	"\fSourceStatus\x12:\n" +
	"\n" +
	"commitment\x18\x01 \x01(\x0e2\x1a.robin.pulse.v1.CommitmentR\n" +
	"commitment\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12!\n" +
	"\fsource_epoch\x18\x03 \x01(\x04R\vsourceEpoch\"\x8f\x01\n" +
	"\x0fSubscriptionAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12!\n" +
	"\ffilter_count\x18\x02 \x01(\rR\vfilterCount\x12:\n" +
	"\n" +
	"commitment\x18\x03 \x01(\x0e2\x1a.robin.pulse.v1.CommitmentR\n" +
	"commitment\"5\n" +
	"\x04Pong\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"\xb3\x03\n" +
	"\vBlockStatus\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12#\n" +
	"\rfeed_sequence\x18\x03 \x01(\x04R\ffeedSequence\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".robin.pulse.v1.BlockStatus.StatusR\x06status\x12+\n" +
	"\x11transaction_count\x18\x05 \x01(\rR\x10transactionCount\x12+\n" +
	"\x11coverage_complete\x18\x06 \x01(\bR\x10coverageComplete\x12\x18\n" +
	"\aattempt\x18\a \x01(\rR\aattempt\x12\x1f\n" +
	"\vparent_hash\x18\b \x01(\fR\n" +
	"parentHash\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x04R\ttimestamp\x12'\n" +
	"\x10base_fee_per_gas\x18\n" +
	" \x01(\x04R\rbaseFeePerGas\"%\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06SEALED\x10\x00\x12\x0f\n" +
	"\vINVALIDATED\x10\x01\"\xd9\x05\n" +
	"\vTransaction\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\x02 \x01(\x04R\x10transactionIndex\x12)\n" +
	"\x10transaction_hash\x18\x03 \x01(\fR\x0ftransactionHash\x12\x1f\n" +
	"\vfrontier_id\x18\x04 \x01(\fR\n" +
	"frontierId\x12\x19\n" +
	"\bgas_used\x18\x05 \x01(\x04R\agasUsed\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x124\n" +
	"\x04kind\x18\a \x01(\x0e2 .robin.pulse.v1.Transaction.KindR\x04kind\x12'\n" +
	"\x04logs\x18\b \x03(\v2\x13.robin.pulse.v1.LogR\x04logs\x12\"\n" +
	"\fprecanonical\x18\t \x01(\bR\fprecanonical\x12\x0e\n" +
	"\x02to\x18\n" +
	" \x01(\fR\x02to\x12\x14\n" +
	"\x05input\x18\v \x01(\fR\x05input\x12#\n" +
	"\rfeed_sequence\x18\f \x01(\x04R\ffeedSequence\x12 \n" +
	"\vprovisional\x18\r \x01(\bR\vprovisional\x12:\n" +
	"\n" +
	"commitment\x18\x0e \x01(\x0e2\x1a.robin.pulse.v1.CommitmentR\n" +
	"commitment\x12\x18\n" +
	"\aattempt\x18\x0f \x01(\rR\aattempt\x12\x15\n" +
	"\x06raw_tx\x18\x10 \x01(\fR\x05rawTx\x12\x14\n" +
	"\x05value\x18\x11 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x12 \x01(\x04R\ttimestamp\x12&\n" +
	"\x0fl1_block_number\x18\x13 \x01(\x04R\rl1BlockNumber\"@\n" +
	"\x04Kind\x12\x0f\n" +
	"\vSTART_BLOCK\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\x13\n" +
	"\x0fSCHEDULED_RETRY\x10\x02\x12\b\n" +
	"\x04FEED\x10\x03\"\x9c\x01\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\fR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x122\n" +
	"\x15transaction_log_index\x18\x04 \x01(\rR\x13transactionLogIndex\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\rR\blogIndex*8\n" +
	"\n" +
	"Commitment\x12\r\n" +
	"\tPROCESSED\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\f\n" +
	"\bRECEIVED\x10\x022\xbf\x01\n" +
	"\x05Pulse\x12R\n" +
	"\tSubscribe\x12 .robin.pulse.v1.SubscribeRequest\x1a\x1f.robin.pulse.v1.SubscribeUpdate(\x010\x01\x12b\n" +
	"\x0fSendTransaction\x12&.robin.pulse.v1.SendTransactionRequest\x1a'.robin.pulse.v1.SendTransactionResponseb\x06proto3"

var (
	file_pulse_proto_rawDescOnce sync.Once
	file_pulse_proto_rawDescData []byte
)

func file_pulse_proto_rawDescGZIP() []byte {
	file_pulse_proto_rawDescOnce.Do(func() {
		file_pulse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulse_proto_rawDesc), len(file_pulse_proto_rawDesc)))
	})
	return file_pulse_proto_rawDescData
}

var file_pulse_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pulse_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pulse_proto_goTypes = []any{
	(Commitment)(0),                         // 0: robin.pulse.v1.Commitment
	(SendTransactionResponse_WaitStatus)(0), // 1: robin.pulse.v1.SendTransactionResponse.WaitStatus
	(BlockStatus_Status)(0),                 // 2: robin.pulse.v1.BlockStatus.Status
	(Transaction_Kind)(0),                   // 3: robin.pulse.v1.Transaction.Kind
	(*SendTransactionRequest)(nil),          // 4: robin.pulse.v1.SendTransactionRequest
	(*SendTransactionResponse)(nil),         // 5: robin.pulse.v1.SendTransactionResponse
	(*ReceivedPosition)(nil),                // 6: robin.pulse.v1.ReceivedPosition
	(*SubscribeRequest)(nil),                // 7: robin.pulse.v1.SubscribeRequest
	(*Subscription)(nil),                    // 8: robin.pulse.v1.Subscription
	(*TransactionFilter)(nil),               // 9: robin.pulse.v1.TransactionFilter
	(*SubscribeUpdate)(nil),                 // 10: robin.pulse.v1.SubscribeUpdate
	(*UpdateBatch)(nil),                     // 11: robin.pulse.v1.UpdateBatch
	(*SourceStatus)(nil),                    // 12: robin.pulse.v1.SourceStatus
	(*SubscriptionAck)(nil),                 // 13: robin.pulse.v1.SubscriptionAck
	(*Pong)(nil),                            // 14: robin.pulse.v1.Pong
	(*BlockStatus)(nil),                     // 15: robin.pulse.v1.BlockStatus
	(*Transaction)(nil),                     // 16: robin.pulse.v1.Transaction
	(*Log)(nil),                             // 17: robin.pulse.v1.Log
	nil,                                     // 18: robin.pulse.v1.Subscription.TransactionsEntry
}
var file_pulse_proto_depIdxs = []int32{
	1,  // 0: robin.pulse.v1.SendTransactionResponse.wait_status:type_name -> robin.pulse.v1.SendTransactionResponse.WaitStatus
	6,  // 1: robin.pulse.v1.SendTransactionResponse.received:type_name -> robin.pulse.v1.ReceivedPosition
	8,  // 2: robin.pulse.v1.SubscribeRequest.replace:type_name -> robin.pulse.v1.Subscription
	18, // 3: robin.pulse.v1.Subscription.transactions:type_name -> robin.pulse.v1.Subscription.TransactionsEntry
	0,  // 4: robin.pulse.v1.Subscription.commitment:type_name -> robin.pulse.v1.Commitment
	16, // 5: robin.pulse.v1.SubscribeUpdate.transaction:type_name -> robin.pulse.v1.Transaction
	13, // 6: robin.pulse.v1.SubscribeUpdate.ack:type_name -> robin.pulse.v1.SubscriptionAck
	14, // 7: robin.pulse.v1.SubscribeUpdate.pong:type_name -> robin.pulse.v1.Pong
	15, // 8: robin.pulse.v1.SubscribeUpdate.block_status:type_name -> robin.pulse.v1.BlockStatus
	12, // 9: robin.pulse.v1.SubscribeUpdate.source_status:type_name -> robin.pulse.v1.SourceStatus
	11, // 10: robin.pulse.v1.SubscribeUpdate.batch:type_name -> robin.pulse.v1.UpdateBatch
	10, // 11: robin.pulse.v1.UpdateBatch.updates:type_name -> robin.pulse.v1.SubscribeUpdate
	0,  // 12: robin.pulse.v1.SourceStatus.commitment:type_name -> robin.pulse.v1.Commitment
	0,  // 13: robin.pulse.v1.SubscriptionAck.commitment:type_name -> robin.pulse.v1.Commitment
	2,  // 14: robin.pulse.v1.BlockStatus.status:type_name -> robin.pulse.v1.BlockStatus.Status
	3,  // 15: robin.pulse.v1.Transaction.kind:type_name -> robin.pulse.v1.Transaction.Kind
	17, // 16: robin.pulse.v1.Transaction.logs:type_name -> robin.pulse.v1.Log
	0,  // 17: robin.pulse.v1.Transaction.commitment:type_name -> robin.pulse.v1.Commitment
	9,  // 18: robin.pulse.v1.Subscription.TransactionsEntry.value:type_name -> robin.pulse.v1.TransactionFilter
	7,  // 19: robin.pulse.v1.Pulse.Subscribe:input_type -> robin.pulse.v1.SubscribeRequest
	4,  // 20: robin.pulse.v1.Pulse.SendTransaction:input_type -> robin.pulse.v1.SendTransactionRequest
	10, // 21: robin.pulse.v1.Pulse.Subscribe:output_type -> robin.pulse.v1.SubscribeUpdate
	5,  // 22: robin.pulse.v1.Pulse.SendTransaction:output_type -> robin.pulse.v1.SendTransactionResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pulse_proto_init() }
func file_pulse_proto_init() {
	if File_pulse_proto != nil {
		return
	}
	file_pulse_proto_msgTypes[3].OneofWrappers = []any{
		(*SubscribeRequest_Replace)(nil),
		(*SubscribeRequest_Ping)(nil),
	}
	file_pulse_proto_msgTypes[5].OneofWrappers = []any{}
	file_pulse_proto_msgTypes[6].OneofWrappers = []any{
		(*SubscribeUpdate_Transaction)(nil),
		(*SubscribeUpdate_Ack)(nil),
		(*SubscribeUpdate_Pong)(nil),
		(*SubscribeUpdate_BlockStatus)(nil),
		(*SubscribeUpdate_SourceStatus)(nil),
		(*SubscribeUpdate_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulse_proto_rawDesc), len(file_pulse_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pulse_proto_goTypes,
		DependencyIndexes: file_pulse_proto_depIdxs,
		EnumInfos:         file_pulse_proto_enumTypes,
		MessageInfos:      file_pulse_proto_msgTypes,
	}.Build()
	File_pulse_proto = out.File
	file_pulse_proto_goTypes = nil
	file_pulse_proto_depIdxs = nil
}
